### ISSUE TITLE
How do I get access to the chart?

### ISSUE THREAD

**Issue by dublinus** [wuct/react-c3-component#25]
For example, let's say I wanted to change the range of an axis. Normally, I would just save the chart in a js variable. How do I do this with this react library?

**Comment by wuct** [comment]
@dublinus To think in React, you would like to modify the chart in a declarative way. In other words, you should just update the config prop and let `<Chart />` do the rest for you.

**Comment by dublinus** [comment]
Well re-rendering for me involves lots of calculations, which takes a long time. I guess the solution for me would be memoizing the calculations so they don't have to be redone every time. Thanks.

**Comment by wuct** [comment]
You can also add pure rendering optimization to the component which owns `<Chart />`, ex: using `[recompose/pure](https://github.com/acdlite/recompose/blob/master/docs/API.md#pure)`.

**Comment by wuct** [comment]
I just close this issue. If you have further questions, feel free to reopen it.

**Comment by prasad4fun** [comment]
Hi,

Not sure how to implement the following example without access to the chart js variable
https://c3js.org/samples/api_flow.html

How do i achieve the same using with this react library?
