### ISSUE TITLE
JSX syntax on render for tooltip html

### ISSUE THREAD

**Issue by nice00xt** [wuct/react-c3-component#32]
well i have a application when this use a dynamic tooltip, this have to change the design depending of the values on the graph, but add inner html into the content of the tooltip is being very hard to refactor because i have a lot of design for the tooltip into many conditions and variables

so i wondering if is possible to add jsx syntax or add a react component to render the html of tooltip into the content of c3

**Comment by wuct** [comment]
@nice00xt It is possible. We can use `data.onmouseover` and `data.onmouseout` to toggle a customized tooltip which can be a React component. However, I don't have time to implement it recently. PRs are welcome :)

**Comment by nice00xt** [comment]
well, someone helped me with that and the way to do this is first import render from react-dom
and into tooltip.content call a function when i can to add the react syntax turn it to string

```
function reactRenderTooltip (component) {
  const el = document.createElement('div')
  render(component, el)
  return el.innerHTML
}
```

```
tooltip: {
   content: function (d) {
      return reactRenderTooltip(
         <Tooltip value={d[0].value} />
      )
   }
}
```
