### ISSUE TITLE
How to use c3 chart functions like .flush(), .resize(), .toggle(), etc

### ISSUE THREAD

**Issue by Sidharth1999** [wuct/react-c3-component#91]
Hello!

I'd like to be able to use functions listed under API in https://c3js.org/reference.html

I'm not sure how to achieve that though - I tried attaching a ref to the Chart component but I get errors when I try to use any function under this._chart.c3.chart.fn

What's the official way to use the API functions with this component?

**Comment by wuct** [comment]
@Sidharth1999 can you provide a sample code by [Code Sandbox](https://codesandbox.io/)?

**Comment by Sidharth1999** [comment]
Sure! This is the link : https://codesandbox.io/embed/async-voice-50cog

**Comment by wuct** [comment]
@Sidharth1999 use `this._chart.chart.toggle`, see:

https://codesandbox.io/embed/gracious-sinoussi-9xexy

**Comment by wuct** [comment]
I think we should add this use case to README.md :)

**Comment by Sidharth1999** [comment]
Thank you so much! And yes, that sounds good :)
